version: '3'
services:

  ticket-scanner:
    image: ticket-scanner
    ports:
      - 8081:8080
    depends_on:
      - redis
    networks:
      - spring-redis-network

  ticket-analyzer:
    image: ticket-analyzer
    ports:
      - 8082:8080
    depends_on:
      - redis
    networks:
      - spring-redis-network

  ticket-validator:
    image: ticket-validator
    depends_on:
      - redis
    networks:
      - spring-redis-network

  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '8001:8001'
      - '6379:6379'
    networks:
      - spring-redis-network

networks:
  spring-redis-network:
    driver: bridge

