boarding-pass:
  stream-key: boarding-pass-stream
  consumer-group: ticket-analyzer
  batch-size: 1000000
  pending-messages:
    check-interval: 0/1 * * ? * *
    timeout: 60000

spring:
  data:
    redis:
      host: redis
      port: 6379

