boarding-pass:
  stream-key: boarding-pass-stream
  consumer-group: ticket-validator
  batch-size: 10000
  pending-messages:
    check-interval: 0/1 * * ? * *
    timeout: 60000

server:
  port: 8082
